services:
  - type: web
    name: red-music
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: JWT_SECRET
        generateValue: true
      - key: NODE_ENV
        value: production
      - key: STORAGE_DIR
        value: /opt/render/project/src/storage
